import { z } from "@/commom/form/pt-zod";

export const internosInsaltSchema = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    cpf: z.string().optional(),
    naturalidade: z.string().optional(),
    rg: z.string().optional(),
    orgaoExpedidor: z.string().optional(),
    dataNascimento: z.coerce.date().optional(),
    etnia: z.string().optional(),
    filiacaoPai: z.string().optional(),
    mae: z.string().optional(),
    enderecoFamiliar: z.string().optional(),
    telefone: z.string().optional(),
    whatsapp: z.string().optional(),
    escolaridade: z.string().optional(),
    profissao: z.string().optional(),
    estadoCivil: z.string().optional(),
    temFamiliaApoio: z.string().optional(),
    nomeFamiliar: z.string().optional(),
    enderecoFamiliar2: z.string().optional(),
    quantosFilhos: z.number().optional(),
    nomesFilhos: z.string().optional(),
    pagaPensao: z.string().optional(),
    religiao: z.string().optional(),
    qualReligiao: z.string().optional(),

    tratamentoPsiquiatrico: z.string().optional(),
    tratamentoPsiquiatricoLocal: z.string().optional(),
    medicamentosPsicotropicos: z.string().optional(),
    medicamentosPsicotropicosMotivo: z.string().optional(),
    medicamentoUsoContinuo: z.string().optional(),
    lesaoFisica: z.string().optional(),
    lesaoFisicaMembro: z.string().optional(),
    doencaRespiratoria: z.string().optional(),
    doencaRespiratoriaTipo: z.string().optional(),
    alergiaAlimentar: z.string().optional(),
    alergiaAlimentarTipo: z.string().optional(),
    alergiaMedicamento: z.string().optional(),
    alergiaMedicamentoTipo: z.string().optional(),
    doencas: z.string().optional(),
    doencaCoracao: z.string().optional(),
    doencaCoracaoTipo: z.string().optional(),
    tentouSuicidio: z.string().optional(),
    autoMutilou: z.string().optional(),
    historicoCancer: z.string().optional(),
    historicoCancerTipo: z.string().optional(),

    foiPreso: z.string().optional(),
    foiPresoMotivo: z.string().optional(),
    respondeProcesso: z.string().optional(),
    respondeProcessoLocal: z.string().optional(),
    tornozeleiraEletronica: z.string().optional(),
    tornozeleiraEletronicaCentralMonitoramento: z.string().optional(),
    cumpriuPena: z.string().optional(),
    desacordoLei: z.string().optional(),
    desacordoLeiMotivo: z.string().optional(),

    alcool: z.string().optional(),
    alcoolInformacoes: z.string().optional(),
    tabaco: z.string().optional(),
    tabacoInformacoes: z.string().optional(),
    substancias: z.string().optional(),
    substanciasMotivoUso: z.string().optional(),
    substanciaMaiorUso: z.string().optional(),

    situacaoRua: z.string().optional(),
    situacaoRuaInformacoes: z.string().optional(),
    chegadaMissaoVida: z.string().optional(),
    chegadaMissaoVidaIgreja: z.string().optional(),
    chegadaMissaoVidaSecretariaGov: z.string().optional(),
    comoSente: z.string().optional(),
    objetivosAcolhido: z.string().optional(),
    outroCentroRecuperacao: z.string().optional(),
    outroCentroRecuperacaoQual: z.string().optional(),
    outroCentroRecuperacaoInformacoes: z.string().optional(),

    autorizacaoGuardaDocumentos: z.string().optional(),
    autorizacaoGuardaDocumentosQuais: z.string().optional(),
    carteiraDocumentosAparencia: z.string().optional(),
    valorMonetarioApresentado: z.string().optional(),
    aparelhoCelularApresentado: z.string().optional(),
    objetoValorApresentado: z.string().optional(),

});

export type InternosInsaltSchema = z.infer<typeof internosInsaltSchema>;