import { z } from "@/commom/form/pt-zod";
import { booleanCoerce } from "@/commom/form/form-validation-utils";

export const filhoSchema = z.object({
    id: z.string().optional(),
    nome: z.string().optional(),
    pagaPensao: booleanCoerce(z.boolean()),
});

export const internosInsaltSchema = z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    cpf: z.string().optional(),
    naturalidade: z.string().optional(),
    rg: z.string().optional(),
    orgaoExpedidor: z.string().optional(),
    dataNascimento: z.coerce.date().optional(),
    etnia: z.string().optional(),
    filiacaoPai: z.string().optional(),
    mae: z.string().optional(),
    enderecoFamiliar: z.string().optional(),
    telefone: z.string().optional(),
    whatsapp: z.string().optional(),
    escolaridade: z.string().optional(),
    profissao: z.string().optional(),
    estadoCivil: z.string().optional(),
    temFamiliaApoio: booleanCoerce(z.boolean()),
    nomeFamiliar: z.string().optional(),
    enderecoFamiliar2: z.string().optional(),
    filhos: z.array(filhoSchema).optional(),
    religiao: booleanCoerce(z.boolean()),
    qualReligiao: z.string().optional(),

    tratamentoPsiquiatrico: booleanCoerce(z.boolean()),
    tratamentoPsiquiatricoLocal: z.string().optional(),
    medicamentosPsicotropicos: booleanCoerce(z.boolean()),
    medicamentosPsicotropicosMotivo: z.string().optional(),
    medicamentoUsoContinuo: booleanCoerce(z.boolean()),
    lesaoFisica: booleanCoerce(z.boolean()),
    lesaoFisicaMembro: z.string().optional(),
    doencaRespiratoria: booleanCoerce(z.boolean()),
    doencaRespiratoriaTipo: z.string().optional(),
    alergiaAlimentar: booleanCoerce(z.boolean()),
    alergiaAlimentarTipo: z.string().optional(),
    alergiaMedicamento: booleanCoerce(z.boolean()),
    alergiaMedicamentoTipo: z.string().optional(),
    doencas: booleanCoerce(z.boolean()),
    doencaCoracao: booleanCoerce(z.boolean()),
    doencaCoracaoTipo: z.string().optional(),
    tentouSuicidio: booleanCoerce(z.boolean()),
    autoMutilou: booleanCoerce(z.boolean()),
    historicoCancer: booleanCoerce(z.boolean()),
    historicoCancerTipo: z.string().optional(),

    foiPreso: booleanCoerce(z.boolean()),
    foiPresoMotivo: z.string().optional(),
    respondeProcesso: booleanCoerce(z.boolean()),
    respondeProcessoLocal: z.string().optional(),
    tornozeleiraEletronica: booleanCoerce(z.boolean()),
    tornozeleiraEletronicaCentralMonitoramento: booleanCoerce(z.boolean()),
    cumpriuPena: booleanCoerce(z.boolean()),
    desacordoLei: booleanCoerce(z.boolean()),
    desacordoLeiMotivo: z.string().optional(),

    alcool: booleanCoerce(z.boolean()),
    alcoolInformacoes: z.string().optional(),
    tabaco: booleanCoerce(z.boolean()),
    tabacoInformacoes: z.string().optional(),
    substancias: booleanCoerce(z.boolean()),
    substanciasMotivoUso: z.string().optional(),
    substanciaMaiorUso: z.string().optional(),

    situacaoRua: booleanCoerce(z.boolean()),
    situacaoRuaInformacoes: z.string().optional(),
    chegadaMissaoVida: z.string().optional(),
    chegadaMissaoVidaIgreja: z.string().optional(),
    chegadaMissaoVidaSecretariaGov: z.string().optional(),
    comoSente: z.string().optional(),
    objetivosAcolhido: z.string().optional(),
    outroCentroRecuperacao: booleanCoerce(z.boolean()),
    outroCentroRecuperacaoQual: z.string().optional(),
    outroCentroRecuperacaoInformacoes: z.string().optional(),

    autorizacaoGuardaDocumentos: z.string().optional(),
    autorizacaoGuardaDocumentosQuais: z.string().optional(),
    carteiraDocumentosAparencia: z.string().optional(),
    valorMonetarioApresentado: z.string().optional(),
    aparelhoCelularApresentado: z.string().optional(),
    objetoValorApresentado: z.string().optional(),

});

export type InternosInsaltSchema = z.infer<typeof internosInsaltSchema>;